{{- if .Values.global.imagePullSecrets.create }}
{{- if or .Values.global.imagePullSecrets.dockerconfigjson (and .Values.global.github.username .Values.global.github.token) }}
apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- if .Values.global.imagePullSecrets.dockerconfigjson }}
  .dockerconfigjson: {{ .Values.global.imagePullSecrets.dockerconfigjson }}
  {{- else }}
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"auth\":\"%s\"}}}" (printf "%s:%s" .Values.global.github.username .Values.global.github.token | b64enc) | b64enc }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
