FROM golang:1.23-alpine3.20 AS builder


WORKDIR /app

# Copy go mod and sum files
COPY go.mod ./
COPY go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o monolith .

# Use a smaller image for the final application
FROM alpine:3.20

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy the binary from builder
COPY --from=builder /app/monolith .

# Expose the application port
EXPOSE 8080

# Command to run the executable
CMD ["./monolith"]